server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://:3306/django?useSSL=false
    username: 
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect